from gym_multi_robot.envs.tiling_pattern_env import TilingPatternEnv
from gym_multi_robot.envs.tiling_pattern_game_alternative import CountTilingPatternEnv
from gym_multi_robot.envs.foraging_env import ForagingEnv